In [20]:
"""- Explorando una imagen en formato de Array 3D
    
    En este ejercicio, simularemos una imagen representada como un **array 3D** en NumPy. En procesamiento de imágenes, un array 3D suele representar una imagen con dimensiones `(altura, anchura, canales)`, donde los **canales** pueden ser **rojo (R), verde (G) y azul (B)** en imágenes a color.
    
    ### Tareas:
    
    1. **Creación del array 3D**
        - Genera un array 3D de tamaño **4x4x3** con valores aleatorios entre **0 y 255** para simular una imagen en formato RGB.
        - Usa `np.random.randint()` para generar valores enteros.
    2. **Indexación en el array 3D**
        - Extrae y muestra:
            - El primer píxel (posición `[0,0]`) con sus valores de color **(R, G, B)**.
            - El último píxel de la imagen (posición `[-1,-1]`).
            - El valor del canal rojo del píxel en la segunda fila y tercera columna.
    3. **Slicing en el array 3D**
        - Extrae y muestra:
            - Toda la primera fila de la imagen (es decir, todos los píxeles de la primera fila con sus valores RGB).
            - Solo los valores del canal azul para todos los píxeles de la imagen.
            - Un recorte central de la imagen, seleccionando las filas y columnas intermedias (por ejemplo, de la posición `[1:3, 1:3, :]`)."""

import numpy as np 
import random 

#Genera un array 3D de tamaño 4x4x3 con valores aleatorios entre 0 y 255 para simular una imagen en formato RGB.
array_3d = np.random.randint(0, 256, (4, 4, 3))

print(array_3d)

#R G B

# El primer píxel (posición [0,0]) con sus valores de color (R, G, B).
print("\n Primer píxel \n",array_3d[0, 0]) 

# El último píxel de la imagen (posición [-1,-1]).
print("\n Último pixel \n",array_3d[-1, -1]) 

# El valor del canal rojo del píxel en la segunda fila y tercera columna.
print("\n El valor del canal rojo del píxel en la segunda fila y tercera columna es: ",array_3d[1, 2, 0])

# Toda la primera fila de la imagen (es decir, todos los píxeles de la primera fila con sus valores RGB).
print("\n La primera fila:\n ",array_3d[0,:])

# Solo los valores del canal azul para todos los píxeles de la imagen.
print("\n Los valores del canal azul para todos los píxeles de la imagen:\n ",array_3d[:,:,2])

# Un recorte central de la imagen, seleccionando las filas y columnas intermedias.
print("\nLas filas y columnas intermedias \n", array_3d[1:3,1:3,:])



[[[  7  84  16]
  [196 253 108]
  [168 208 135]
  [244  22 124]]

 [[154  41 103]
  [213  30 161]
  [ 81 251  24]
  [199  79  38]]

 [[146 179 210]
  [233 190 141]
  [ 94 186 145]
  [255 104 150]]

 [[242  20  57]
  [ 84 139  89]
  [199  63  41]
  [ 22 252 127]]]

 Primer píxel 
 [ 7 84 16]

 Último pixel 
 [ 22 252 127]

 El valor del canal rojo del píxel en la segunda fila y tercera columna es:  81

 La primera fila:
  [[  7  84  16]
 [196 253 108]
 [168 208 135]
 [244  22 124]]

 Los valores del canal azul para todos los píxeles de la imagen:
  [[ 16 108 135 124]
 [103 161  24  38]
 [210 141 145 150]
 [ 57  89  41 127]]

Las filas y columnas intermedias 
 [[[213  30 161]
  [ 81 251  24]]

 [[233 190 141]
  [ 94 186 145]]]
