In [3]:
"""Crear un array unidimensional con el nombre de los productos:** Tienes una lista de 5 productos: `"Smartphone"`, `"Tablet"`, `"Laptop"`, `"Auriculares"`, `"Teclado"`. Imprímelo."""

import numpy as np

productos = np.array(["Smartphone", "Tablet", "Laptop", "Auriculares", "Teclado"])
print(productos)


['Smartphone' 'Tablet' 'Laptop' 'Auriculares' 'Teclado']


In [21]:
"""2. **Crear un array bidimensional con la cantidad en stock de cada producto:** La tienda tiene el siguiente stock de productos:
    
    ```bash
    Smartphone - 50
    Tablet - 30
    Laptop - 15
    Auriculares - 40
    Teclado - 60
    ```
    
    Crea un array bidimensional donde cada fila represente un producto y las columnas representen el stock disponible en diferentes almacenes. Imprime el array."""

productos_2d = np.array([
    ["Smartphone",50], ["Tablet",30], ["Laptop",30], ["Auriculares",90], ["Teclado",70]
    ])
print(productos_2d)

[['Smartphone' '50']
 ['Tablet' '30']
 ['Laptop' '30']
 ['Auriculares' '90']
 ['Teclado' '70']]


In [9]:
"""3. **Crear un array tridimensional para registrar las ventas de cada producto durante una semana:** Imagina que tienes un registro de ventas para cada uno de los 5 productos durante 3 días de la semana. Cada capa del array representará un día de ventas y las columnas serán las cantidades vendidas para cada producto:"""

productos_3d = np.array ([[
    [5, 3, 2, 6, 4],
    [7, 4, 1, 8, 5],
    [6, 2, 3, 5, 4]
]])
print(f"Las ventas de 3 días son ",productos_3d)

[[[5 3 2 6 4]
  [7 4 1 8 5]
  [6 2 3 5 4]]]


In [12]:
"""Crear un array de ceros para los productos no vendidos hoy: Los productos que no se han vendido hoy deben estar en cero. Crea un array de ceros para representar la cantidad de productos no vendidos de la tienda hoy. Imprime el array."""


productos_0 = np.zeros ([1,5])
print(productos_0) 

[[0. 0. 0. 0. 0.]]


In [25]:
"""Crear un array de unos para los productos que están en promoción: Los productos en promoción tienen un valor de 1, mientras que los que no están en promoción tienen 0. Crea un array de unos y ceros, donde los productos en promoción tienen el valor 1. Los productos en promoción son el "Smartphone" y el "Teclado". Imprímelo."""

promocion = np.ones((1,5))
promocion[0,1:4] = 0
print(promocion)

[[1. 0. 0. 0. 1.]]


In [26]:
"""Crear un array con un rango de precios de productos: La tienda tiene productos cuyo precio varía entre 50 y 1000 unidades monetarias. Crea un array con los precios de los productos, usando la función np.arange, y un paso de 50 unidades. Imprímelo."""

precios = np.arange(50, 1001, 50)
print(precios)

[  50  100  150  200  250  300  350  400  450  500  550  600  650  700
  750  800  850  900  950 1000]


In [31]:
"""Crear un array de precios aleatorios: Crea un array con precios aleatorios para los productos entre 100 y 500 unidades monetarias, de tamaño 5. Imprímelo."""

import random
precio_aleatorio = np.random.randint(100, 500, 5)
print(precio_aleatorio)

[150 385 344 115 411]


In [32]:
"""Generar un array de números enteros aleatorios para la cantidad vendida: Utiliza np.random.randint para crear un array de 5 elementos, con valores aleatorios entre 1 y 10, que representen las unidades vendidas de cada producto hoy. Imprímelo."""

import random
cantidad_aleatorio = np.random.randint(1, 10, 5)
print(cantidad_aleatorio)

[3 9 7 4 8]


In [34]:
"""Crear un array vacío para almacenar los valores de descuento: Crea un array vacío de tamaño 5x1 para almacenar los descuentos que se aplicarán a cada producto. Imprímelo."""

descuento = np.empty((5,1))
print(descuento) 

[[1.]
 [0.]
 [0.]
 [0.]
 [1.]]


In [35]:
"""Generar un array con valores espaciados para analizar el cambio en las ventas: Imagina que deseas analizar cómo cambian las ventas en diferentes intervalos de tiempo (por ejemplo, cada 2 horas). Utiliza np.linspacepara generar un array con 5 puntos de venta, distribuidos entre 0 y 1000 unidades, representando las ventas totales del día. Imprímelo."""

ventas_totales = np.linspace(0, 1000, 5)
print(ventas_totales) 

[   0.  250.  500.  750. 1000.]


In [1]:
!jupyter nbconvert --to pdf notebook_inicial.ipynb

[NbConvertApp] Converting notebook notebook_inicial.ipynb to pdf
[NbConvertApp] Writing 30675 bytes to notebook.tex
[NbConvertApp] Building PDF
[NbConvertApp] Running xelatex 3 times: ['xelatex', 'notebook.tex', '-quiet']
[NbConvertApp] Running bibtex 1 time: ['bibtex', 'notebook']
[NbConvertApp] WARNING | b had problems, most likely because there were no citations
[NbConvertApp] PDF successfully created
[NbConvertApp] Writing 28851 bytes to notebook_inicial.pdf
