In [3]:
import numpy as np

# Crear un array de 25 elementos
array = np.arange(25)

# 2. Cambiar la forma del array a una matriz 5x5
matriz_5x5 = array.reshape(5, 5)
print("Matriz 5x5:")
print(matriz_5x5)

# 2. Cambiar la forma del array a una matriz 2x4
matriz_2x4 = array[:8].reshape(2, 4)
print("\nMatriz 2x4:")
print(matriz_2x4)

# 3. Aplanar el array a un vector
vector_aplanado = matriz_5x5.flatten()
print("\nArray aplanado (vector):")
print(vector_aplanado)

# 4. Transponer el array
matriz_transpuesta = matriz_5x5.T
print("\nMatriz 5x5 transpuesta:")
print(matriz_transpuesta)



Matriz 5x5:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

Matriz 2x4:
[[0 1 2 3]
 [4 5 6 7]]

Array aplanado (vector):
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]

Matriz 5x5 transpuesta:
[[ 0  5 10 15 20]
 [ 1  6 11 16 21]
 [ 2  7 12 17 22]
 [ 3  8 13 18 23]
 [ 4  9 14 19 24]]


In [14]:
#Operaciones con arrays

#Crea 2 arrays de matrices 2x2
array1 = np.array ([[1,2,3],[6,2,7]])
array2 = np.array ([[4,5,6],[2,1,5]])

#Suma
print(f"Suma de arrays: \n",array1 + array2)

#Resta
print(f"Resta de arrays: \n",array1 - array2)

#Multiplicación
print(f"Multiplicación de arrays: \n",array1 * array2)

#División
print(f"División de arrays: \n",array1 / array2)

#Operación con escalar
print(f"Multiplicación de array por escalar: \n",array1 * 6)



Suma de arrays: 
 [[ 5  7  9]
 [ 8  3 12]]
Resta de arrays: 
 [[-3 -3 -3]
 [ 4  1  2]]
Multiplicación de arrays: 
 [[ 4 10 18]
 [12  2 35]]
División de arrays: 
 [[0.25 0.4  0.5 ]
 [3.   2.   1.4 ]]
Multiplicación de array por escalar: 
 [[ 6 12 18]
 [36 12 42]]


In [21]:
#Suma acumulada (Se suman los valores de la lista 1 por 1)

#Crea un vector con 25 elementos con valores aleatorios
import numpy as np
import random

#vector de 25 elementos aleatorios
vector = np.random.randint(1, 100, 25)
print(vector)

#Suma acumulada
suma_acumuladas = np.cumsum(vector)

print("La suma acumulada de los números aleatorios es : ", suma_acumuladas)

#vector de 25 elementos aleatorios flotantes
vector_flotante = np.random.rand(1, 100, 25)
print("La suma acumulada de los números aleatorios flotantes es : ",vector_flotante)





[59 45 46 56 37 50 75 15 85 60 60 77 67 69 21 88 40 47 49 41 20  6 94 95
 83]
La suma acumulada de los números aleatorios es :  [  59  104  150  206  243  293  368  383  468  528  588  665  732  801
  822  910  950  997 1046 1087 1107 1113 1207 1302 1385]
La suma acumulada de los números aleatorios flotantes es :  [[[0.77913907 0.96934575 0.79450013 ... 0.81019162 0.69196692 0.44981401]
  [0.87046692 0.86606724 0.61027619 ... 0.16025319 0.95872246 0.14431841]
  [0.76638597 0.97911019 0.57542628 ... 0.45962247 0.44079581 0.97025996]
  ...
  [0.75267835 0.53359187 0.99080723 ... 0.39827558 0.29336845 0.47955772]
  [0.26837062 0.77957129 0.30179009 ... 0.78943889 0.45668489 0.91963346]
  [0.58078432 0.61245583 0.80328776 ... 0.14780798 0.22555927 0.85297949]]]


In [23]:
#supongamos que tenemos un conjunto de datos de discos de música con el siguiente formato: [número de canciones, premios grammy, ventas en miles de euros]. Cada disco es un vector en un espacio tridimensional. Dado un nuevo disco de nuestra discográfica queremos evaluar qué disco existente es más similar en términos de distancia euclidiana.

disco_1 = np.array([49, 4, 250])  # número_canciones, premios_grammy, ventas_miles_euros
disco_2 = np.array([60, 1, 212]) 
disco_3 = np.array([110, 2, 100]) 

nuevo_disco = np.array([80, 3, 190])

# vectores
discos = np.array([disco_1, disco_2, disco_3])

# distancia euclidiana entre dos vectores
def distancia(v1, v2):
    return np.sqrt(np.sum((v1 - v2) ** 2)) 

# Calcular distancia euclidiana
distancias = [distancia(nuevo_disco, discos) for disco in discos]

# Encontrar el disco mas parecido
indice_disco_mas_parecido = np.argmin(distancias)  # Usamos np.argmin() para encontrar el vector más cercano en términos de distancia. Esta función devuelve el índice del menor valor en un array.
disco_mas_parecido = discos[indice_disco_mas_parecido]

print(f"El disco más aprecido es : {disco_mas_parecido} con una distancia de {distancias[indice_disco_mas_parecido]:.2f}")




El disco más aprecido es : [ 49   4 250] con una distancia de 120.21


In [11]:
#Crea dos vector con numeros aleatorios

# 1. Producto Punto (Dot Product)
import numpy as np
import random

vector1 = np.random.randint(1, 10, 3)
vector2 = np.random.randint(1, 10, 3)

producto_punto = np.dot(vector1, vector2)
print(vector1)
print(vector2)

print("Producto punto:", producto_punto)

# 2. Producto Cruzado (Cross Product)

vector3 = np.random.randint(1, 10, 3)
vector4 = np.random.randint(1, 10, 3)

producto_cruzado = np.cross(vector3, vector4)
print(vector3)
print(vector4)

print("Producto cruzado:", producto_cruzado)

[2 2 1]
[4 7 1]
Producto punto: 23
[6 6 2]
[9 6 1]
Producto cruzado: [ -6  12 -18]


In [20]:
#Distancia Euclidiana (L2) y Distancia Manhattan (L1)

#Del 5 al 20 dando un salto de 5
#Del 100 al 400 dando un salto 100

import numpy as np
import random

A = np.arange(5, 21, 5)
B = np.arange(100, 401, 100)

# Calcular distancia usando la norma L2
distancia = np.linalg.norm(B - A)

print(f"Distancia Euclidiana entre A y B:, {distancia:.2f}")

# Calculamos la norma L1 (Manhattan)
norma1_L1 = np.linalg.norm(A, ord=1)
norma2_L1 = np.linalg.norm(B, ord=1)

print(f"Norma L1 del vector A:, {norma1_L1:.2f}")
print(f"Norma L1 del vector B:, {norma2_L1:.2f}")

#Calcular distancia al origen
distancia_origenA = np.sqrt(np.sum(A**2))
print(f"Distancia al origen del vector A:, {distancia_origenA:.2f}")

distancia_origenB = np.sqrt(np.sum(B**2))
print(f"Distancia al origen del vector B:, {distancia_origenB:.2f}")

Distancia Euclidiana entre A y B:, 520.34
Norma L1 del vector A:, 50.00
Norma L1 del vector B:, 1000.00
Distancia al origen del vector A:, 27.39
Distancia al origen del vector B:, 547.72
