In [9]:
"""Eres un analista de rendimiento deportivo y tienes un equipo de **fútbol** que ha jugado **una temporada completa**. Para evaluar a cada jugador, has recopilado sus estadísticas en diferentes categorías:

- **Goles marcados**
- **Asistencias**
- **Pases completados**
- **Regates exitosos**
- **Tiros a puerta**

Sin embargo, los valores en cada categoría tienen escalas diferentes, por lo que es difícil comparar directamente el desempeño de los jugadores. Para resolver este problema, aplicarás la **normalización con la norma L2**, lo que permitirá convertir todas las estadísticas a una escala comparable.

### **Objetivo del ejercicio**

1. Representar el rendimiento de los jugadores como una matriz en NumPy.
2. Aplicar la **normalización L2** a cada jugador para escalar sus valores entre 0 y 1 mientras se mantiene la proporción relativa.
3. Comparar los jugadores después de la normalización.

### **Datos de entrada**

Supongamos que tenemos los datos de 5 jugadores:

| Jugador | Goles | Asistencias | Pases | Regates | Tiros a puerta |
| --- | --- | --- | --- | --- | --- |
| Jugador 1 | 10 | 7 | 300 | 25 | 40 |
| Jugador 2 | 15 | 10 | 250 | 30 | 50 |
| Jugador 3 | 5 | 12 | 280 | 20 | 35 |
| Jugador 4 | 8 | 6 | 310 | 15 | 38 |
| Jugador 5 | 12 | 9 | 270 | 28 | 45 |

Cada jugador es un **vector** con 5 componentes. Aplicaremos la **norma L2** para normalizar sus estadísticas.

### **Tareas**

1. Representar los datos como una matriz en NumPy.
2. Aplicar la normalización L2 a cada jugador (por filas, usando `axis=1`).
3. Mostrar los valores normalizados y analizar cómo se comparan los jugadores tras la normalización."""

import numpy as np

jugadores = np.array([
[10, 7, 300, 25, 40],
[15, 10, 250, 30, 50],
[5, 12, 280, 20, 35],
[8, 6, 310, 15, 38],
[12, 9, 270, 28, 45]])

print("Jugadores: \n",jugadores,"\n")

L2 = np.sum(jugadores,axis=1,keepdims=True)
print("L2 de los jugadores es:\n", L2)

# Se comparan sumando todos sus valores y dividiendo por el L2 de cada jugador

#P3
L2_axis0 = np.sum(jugadores,axis=0,keepdims=True)
print("\nL2 con axis=0 de los jugadores es:\n", L2_axis0)


Jugadores: 
 [[ 10   7 300  25  40]
 [ 15  10 250  30  50]
 [  5  12 280  20  35]
 [  8   6 310  15  38]
 [ 12   9 270  28  45]] 

L2 de los jugadores es:
 [[382]
 [355]
 [352]
 [377]
 [364]]

L2 con axis=0 de los jugadores es:
 [[  50   44 1410  118  208]]


### Preguntas

- ¿Cómo cambian los valores después de la normalización?
    No cambian, si no que se suman
- ¿Por qué la normalización L2 es útil cuando los datos tienen escalas diferentes?
    Porque transforma los datos de manera que todos los valores se ajustan proporcionalmente.
- ¿Qué pasaría si normalizamos por **columnas (axis=0)** en lugar de por filas?
    L2_axis0