In [22]:
"""Eres un ingeniero de datos en un equipo de Fórmula 1 y debes analizar el rendimiento de **10 pilotos** en **5 carreras**. Para ello, trabajarás con matrices en NumPy para transformar los datos y extraer información útil.

### **Tareas:**

1. **Representar los datos** en un array bidimensional de NumPy donde cada fila sea un piloto y cada columna una carrera.
2. **Transformación de arrays:**
    - Reorganiza la matriz con `.reshape()` para analizar los datos de otra manera.
    - Usa `.ravel()` o `.flatten()` para convertir la matriz en un array 1D.
3. **Operaciones aritméticas:**
    - Calcula el promedio de posiciones por piloto y por carrera (`axis=0` y `axis=1`).
    - Aplica una penalización sumando un valor a cada posición y recalculando los valores.
4. **Producto escalar:**
    - Modela el rendimiento de dos pilotos como vectores y calcula su similitud mediante el **producto escalar**.
5. **Producto cruzado:**
    - Representa las posiciones de dos pilotos en las primeras tres carreras como vectores 3D y calcula su **producto cruzado**, interpretando el resultado en términos de diferencias de rendimiento.
6. **Extra bonus:**
    - Normaliza los datos usando la **norma L2** (`np.linalg.norm()`) para comparar el rendimiento de los pilotos en diferentes circuitos."""

import numpy as np

pilotos = np.array([
    [1, 6, 10, 4, 10],
    [2, 5, 7, 3, 9],
    [3, 4, 1, 1, 8],
    [10, 2, 2, 2, 7],
    [4, 3, 3, 10,6],
    [5, 9, 4, 8, 5],
    [6, 8, 9, 9, 4],
    [7, 7, 8, 7, 3],
    [8, 1, 6, 6, 2],
    [9, 10, 5, 5, 1]
    ])


print("Array bidimensional:\n", pilotos)

# Reorganiza la matriz con .reshape() para analizar los datos de otra manera.
pilotos_reshape = pilotos.reshape(5,10)
print("\n Reshape \n",pilotos_reshape)

# Usa .ravel() o .flatten() para convertir la matriz en un array 1D.
pilotos_ravel = pilotos.ravel()
print("\n Ravel \n",pilotos_ravel)

# Calcula el promedio de posiciones por piloto y por carrera (axis=0 y axis=1).
promedio_piloto = np.mean(pilotos, axis=1)
promedio_carrera = np.mean(pilotos, axis=0)
print("\n Promedio por piloto \n",promedio_piloto)
print("\n Promedio por carrera \n",promedio_carrera)

# Aplica una penalización sumando un valor a cada posición y recalculando los valores.
pilotos_penalizado = pilotos + 2
print("\n Pilotos penalizados \n",pilotos_penalizado)

# Modela el rendimiento de dos pilotos como vectores y calcula su similitud mediante el producto escalar.
piloto1 = pilotos[0]
piloto2 = pilotos[1]

producto_escalar = np.dot(piloto1, piloto2)
print("\n Producto escalar \n",producto_escalar)

# Representa las posiciones de dos pilotos en las primeras tres carreras como vectores 3D y calcula su producto cruzado, interpretando el resultado en términos de diferencias de rendimiento.
piloto1_3d = piloto1[:3]
piloto2_3d = piloto2[:3]

producto_cruzado = np.cross(piloto1_3d, piloto2_3d)
print("\n Producto cruzado \n",producto_cruzado)

# Normaliza los datos usando la norma L2 (np.linalg.norm()) para comparar el rendimiento de los pilotos en diferentes circuitos.
piloto1_norm = pilotos[0] / np.linalg.norm(pilotos[0])
piloto2_norm = pilotos[1] / np.linalg.norm(pilotos[1])
print(f"\n Norma L2 del piloto 1: \n {piloto1_norm}")
print(f"\n Norma L2 del piloto 2: \n {piloto2_norm}")


Array bidimensional:
 [[ 1  6 10  4 10]
 [ 2  5  7  3  9]
 [ 3  4  1  1  8]
 [10  2  2  2  7]
 [ 4  3  3 10  6]
 [ 5  9  4  8  5]
 [ 6  8  9  9  4]
 [ 7  7  8  7  3]
 [ 8  1  6  6  2]
 [ 9 10  5  5  1]]

 Reshape 
 [[ 1  6 10  4 10  2  5  7  3  9]
 [ 3  4  1  1  8 10  2  2  2  7]
 [ 4  3  3 10  6  5  9  4  8  5]
 [ 6  8  9  9  4  7  7  8  7  3]
 [ 8  1  6  6  2  9 10  5  5  1]]

 Ravel 
 [ 1  6 10  4 10  2  5  7  3  9  3  4  1  1  8 10  2  2  2  7  4  3  3 10
  6  5  9  4  8  5  6  8  9  9  4  7  7  8  7  3  8  1  6  6  2  9 10  5
  5  1]

 Promedio por piloto 
 [6.2 5.2 3.4 4.6 5.2 6.2 7.2 6.4 4.6 6. ]

 Promedio por carrera 
 [5.5 5.5 5.5 5.5 5.5]

 Pilotos penalizados 
 [[ 3  8 12  6 12]
 [ 4  7  9  5 11]
 [ 5  6  3  3 10]
 [12  4  4  4  9]
 [ 6  5  5 12  8]
 [ 7 11  6 10  7]
 [ 8 10 11 11  6]
 [ 9  9 10  9  5]
 [10  3  8  8  4]
 [11 12  7  7  3]]

 Producto escalar 
 204

 Producto cruzado 
 [-8 13 -7]

 Norma L2 del piloto 1: 
 [0.06286946 0.37721677 0.62869461 0.25147785 0.628694